### ISSUE TITLE
서버 연결 문제

### ISSUE THREAD

**Issue by neco1004oni** [hyunwoongko/kochat#32]
[2024-12-06 10:34:01,936] ERROR in app: Exception on /request_chat/나/한국 날씨 [GET]
Traceback (most recent call last):
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\kochat\app\kochat_api.py", line 83, in request_chat
    prep = self.dataset.load_predict(text, self.embed_processor)
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\kochat\data\dataset.py", line 101, in load_predict
    text = self.prep.tokenize(text, train=False)  # 토크나이징
  File "C:\Users\PC\anaconda3\envs\kochat2\lib\site-packages\kochat\data\preprocessor.py", line 106, in tokenize
    if self.naver_fix:
AttributeError: 'Preprocessor' object has no attribute 'naver_fix'
127.0.0.1 - - [06/Dec/2024 10:34:01] "GET /request_chat/나/한국%20날씨 HTTP/1.1" 500 -
![image](https://github.com/user-attachments/assets/1fbe749a-01f3-4e92-848b-9d4e6a32d156)

실행은 잘 되었는데 이름 설정 후 간단하게 한국 날씨라고 질문했는데 서버와 연결할수없다는 에러가 뜨네요
뭔가 추가로 API에대해 KEY를 설정하거나 그런게 있을까요?

**Comment by neco1004oni** [comment]
해결됬습니다 문제가 네이버 맞춤법 검사기에대한 에러이며 이제는 지원하지 않는 건지 모르겠네요.. 일단 Preprocessor.py에서
self.naver_fix = naver_fix 이부분을 지우고 self.naver_fix = False 로 사용 안하는 방법으로 진행하니 문제가 해결됬습니다.
